const palette = {
  green: "#1B7A4E",
  greenLight: "#2DA06A",
  greenDark: "#145C3A",
  cream: "#FFF8F0",
  warmWhite: "#FEFCF9",
  charcoal: "#1A1A1A",
  darkSurface: "#2A2A2A",
  darkCard: "#333333",
  gray100: "#F5F5F5",
  gray200: "#E8E8E8",
  gray400: "#AAAAAA",
  gray600: "#666666",
  red: "#E74C3C",
  whatsappGreen: "#25D366",
};

export default {
  light: {
    text: palette.charcoal,
    textSecondary: palette.gray600,
    background: palette.warmWhite,
    surface: "#FFFFFF",
    card: "#FFFFFF",
    tint: palette.green,
    tintLight: palette.greenLight,
    border: palette.gray200,
    inputBg: palette.gray100,
    tabIconDefault: palette.gray400,
    tabIconSelected: palette.green,
    danger: palette.red,
    whatsapp: palette.whatsappGreen,
    quantityBg: palette.cream,
  },
  dark: {
    text: "#FFFFFF",
    textSecondary: "#AAAAAA",
    background: palette.charcoal,
    surface: palette.darkSurface,
    card: palette.darkCard,
    tint: palette.greenLight,
    tintLight: palette.green,
    border: "#3A3A3A",
    inputBg: palette.darkSurface,
    tabIconDefault: "#666666",
    tabIconSelected: palette.greenLight,
    danger: palette.red,
    whatsapp: palette.whatsappGreen,
    quantityBg: palette.darkSurface,
  },
};
